services:
  mysql-dev:
    image: mysql:8.0
    container_name: karriera-job-board-db-dev
    restart: always
    env_file:
      - ../envs/.env.development
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    volumes:
      - mysql_data-dev:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  job-board-dev:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: karriera-job-board-dev
    restart: always
    env_file:
      - ../envs/.env.development
    ports:
      - '${PORT:-3000}:3000'
    volumes:
      - ../:/app
      - /app/node_modules
    depends_on:
      - mysql-dev
volumes:
  mysql_data-dev:
