services:
  mysql-dev:
    image: mysql:8.4
    container_name: karriera-job-board-db-dev
    restart: always
    env_file:
      - ../envs/.env.development
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    volumes:
      - mysql_data-dev:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  job-board-dev:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: karriera-job-board-dev
    restart: always
    env_file:
      - ../envs/.env.development
    ports:
      - '${PORT:-3000}:3000'
    volumes:
      - ../:/app
      - /app/node_modules
    depends_on:
      - mysql-dev

  job-board-kafka:
    image: confluentinc/cp-kafka:latest
    container_name: karriera-job-board-kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: job-board-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://job-board-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_DIRS: /tmp/kafka-logs
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISN_REPLICAS: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CLUSTER_ID: 'BhIjNvTYTtajQYAvYOA7yw'
    tmpfs:
      - /tmp/kafka-logs
    depends_on:
      job-board-zookeeper:
        condition: service_healthy
    healthcheck:
      test:
        ['CMD-SHELL', 'kafka-topics --bootstrap-server localhost:9092 --list']
      interval: 5s
      timeout: 10s
      retries: 5

  job-board-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: karriera-job-board-zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disable security (use only for local dev)
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: unless-stopped

volumes:
  mysql_data-dev:
  zookeeper_data:
  elasticsearch-data:
    driver: local
