services:
  mysql-dev:
    image: mysql:8.0
    container_name: karriera-job-board-db
    restart: always
    env_file:
      - ../apps/job-board/envs/.env.development
    ports:
      - '${MYSQL_PORT:-3306}:3306' # Use default 3306 if MYSQL_PORT is not set
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
