// Tokens
export const MESSAGE_CLIENT = 'MESSAGE_CLIENT' as const;
export const JOB_POST_EVENTS_PRODUCER_LOGGER =
  'JOB_POST_EVENTS_PRODUCER_LOGGER';
export const JOB_POST_SERVICE_LOGGER = 'JOB_POST_SERVICE_LOGGER';
